### ISSUE TITLE
Improve support of MATLAB structure variables

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#2105]
**Reported by beutlich on 11 Nov 2016 07:16 UTC**
#1840 added the feature to read variables from MATLAB structure variables to MSL 3.2.2. However the feature currently is limitated to 1x1 structures. It would be easy to generalize the feature for arbitrary two-dimensional structures by giving giving the structure element, e.g., `a.b` could be generalized to `a(1,1).b` where `a` is a structure and `b` is a real array. Then `a(2,3).b(4,5).c` could also be valid inputs.

If this feature is not considered, then at least the current error message for mxn structures should be improved to point to the dimensional problem and not to the type problem.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2105

**Comment by tbeu** [comment]
@Claytex Thanks for the nice blog at http://www.claytex.com/blog/reading-structures-from-mat-files. Do you have any feature requests?

**Comment by beutlich** [comment]
@HansOlsson @sjoelund I kindly ask for your input since I have no idea who else cares and whom I could ask. Thanks for your feedback. I appreciate it.

Options are:
1. Do not add support for multidimensional structs, but improve error message.
2. Add support for multidimensional structs and use MATLAB syntax for array subscription
3. Add support for multidimensional structs and use Modelica syntax for array subscription
4. Use both MATLAB and Modelica syntax 

Which one do you prefer?

**Comment by beutlich** [comment]
@Claytex @HansOlsson @MartinOtter Any feedback? Otherwise I will simply close as wontfix.

**Comment by HansOlsson** [comment]
I have no specific opinion at this time

**Comment by beutlich** [comment]
OK, no need to work on it (now), if there is no public interest.
