### ISSUE TITLE
%name field missing in Modelica.Blocks.Logical

### ISSUE THREAD

**Issue by ceraolo** [modelica/Modelica#2237]
In Modelica.Blocks.Logical there are 8 models without a %name field:
GreaterThreshold, GreaterEqualThreshold,  LessThreshold, LessEqualThreshold, Greater, GreaterEqual,  Less, LessEqual.

I think it is a good idea that all MSL models have a name field included the ones listed above. It eases looking at the output variables in tools.

**Comment by beutlich** [comment]
Not sure if this will happen, since Blocks.Logical is superseded by Blocks.MathBoolean, see #2164.

**Comment by dietmarw** [comment]
@ceraolo has a point here though. I mean even if there is something planned (whenever that should be) `MathBoolean` can not really replace `Logical` and so the library officer (@otter) should make up his mind if there is a real chance to deprecate `Logical` or not. In the further case the some of the blocks from `Logical` need to be implemented in `MathBoolean` (there are still some missing) and in the latter case it should simply be fixed with whatever issues occur. Starting with removing the useless comment that is referred to in #2164.

**Comment by AHaumer** [comment]
resolved in master
