### ISSUE TITLE
Problem with potentialRoot in Modelica.Electrical.QuasiStationary.Machines.BasicMachines.Components.PartialCore

### ISSUE THREAD

**Issue by HansOlsson** [modelica/Modelica#2280]
In Modelica.Electrical.QuasiStationary.Machines.BasicMachines.Components.PartialCore I noticed the following:
```
  Connections.potentialRoot(plug_p1.reference);
  Connections.potentialRoot(plug_p2.reference);
  Connections.potentialRoot(plug_p3.reference);
```

This is indicates that we can potentially use them as a reference - without providing a reference in that case. I don't understand how that is supposed to work. 

To me it seems that either these three equations should be removed (I believe that to be the correct solution), or there should be matching `isRoot `equations - similarly as in the `Modelica.Electrical.QuasiStationary.SinglePhase.Basic.Ground`-model.

**Comment by AHaumer** [comment]
I believe you're fight Hans, it seems Iäve gone too far.
The transformer that uses the core model could be connected either on the primary side (plug_p1, plug_n1) or on the secondary side (plug_p2 and plug_p3, plug_n2 and plug_n3) to a source (which defines a root), and on the other side to a load. For sure bith sides have to have the same reference (i.e. frequency). But since there exist non-breakable branches between primary side and secondary side there's no need to define potential roots. 
Hans please correct me if I'm wrong. 
I'll try to remove these three equations and run some tests.
