### ISSUE TITLE
Non-existent class referenced in choices annotation in Modelica.Mechanics.MultiBody.Examples.Loops.Utilities.EngineV6_analytic

### ISSUE THREAD

**Issue by harmanpa** [modelica/Modelica#2317]
In Modelica.Mechanics.MultiBody.Examples.Loops.Utilities.EngineV6_analytic there is a choices annotation for redeclaring the Cylinder type. One of the options is "Modelica.Mechanics.MultiBody.Examples.Loops.Utilities.Cylinder_analytic", however no such class exists.

https://github.com/modelica/Modelica/blob/f1e1cded603cf9dc8ac8f48da4fa61cecf6df129/Modelica/Mechanics/MultiBody/Examples/Loops/Utilities.mo#L746

**Comment by HansOlsson** [comment]
The correction is not clear.
It is not clear why this model Modelica.Mechanics.MultiBody.Examples.Loops.Utilities.Cylinder_analytic would be needed in addition to Modelica.Mechanics.MultiBody.Examples.Loops.Utilities.Cylinder_analytic_CAD

But without Cylinder_analytic it seems odd to have a choice-annotation with only one choice - which is the default.

So one possibility is to just remove the entire choices-part.

**Comment by beutlich** [comment]
c24c607b0e1591abce46b84e734e39aa6e7d2b9a was the commit that uncommented the choices annotation. (10 years ago). Telling from the commit message it is not clear if it was by intention or not.
Since the CylinderBase model also contains CAD part visualization, I agreed to comment the choices annotation again.
