### ISSUE TITLE
PowerConverters

### ISSUE THREAD

**Issue by AHaumer** [modelica/Modelica#2417]
I have some minor enhancements to PowerConverters, as well as an implementation of a step up (boost) converter. I'll create a pull request.

**Comment by dietmarw** [comment]
@AHaumer You normally don't need to open up an additional issue for a PR since the PR itself serves as an issue with a discussion thread. So simply create a PR and describe what it does and its purpose which then can be discussed and approved by somebody else to be accepted. Just saves a bit of work ;-)

**Comment by beutlich** [comment]
Can this be closed then?

**Comment by beutlich** [comment]
Can you please edit the issue caption to make clear what the exact enhancement is? For example: Add step up chopper to PoverConverters. This makes it easier when collecting the relevant information for the release notes.
